using Npgsql;
using System.Text.Json;

namespace FloodZoneDb.Client;

public sealed class FloodZoneConnection
{
    private readonly string _connectionString;

    public FloodZoneConnection(string connectionString)
    {
        if (string.IsNullOrWhiteSpace(connectionString))
            throw new ArgumentException("Строка подключения не задана.", nameof(connectionString));

        _connectionString = connectionString;
    }

    public static FloodZoneConnection FromEnvironment()
    {
        var connectionString = Environment.GetEnvironmentVariable("FLOODZONE_CONN");
        if (string.IsNullOrWhiteSpace(connectionString))
            throw new InvalidOperationException(
                "Переменная окружения FLOODZONE_CONN не задана.");

        return new FloodZoneConnection(connectionString);
    }

    public async Task<bool> CanConnectAsync(CancellationToken cancellationToken = default)
    {
        DatabaseLogger.Info("Проверка подключения к PostgreSQL.");
        try
        {
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand("select 1", connection);
            var result = Convert.ToInt32(await command.ExecuteScalarAsync(cancellationToken)) == 1;
            DatabaseLogger.Info("Проверка подключения завершена: " + result + ".");
            return result;
        }
        catch (Exception ex)
        {
            DatabaseLogger.Error("Ошибка проверки подключения к PostgreSQL.", ex);
            throw;
        }
    }

    public async Task EnsureDatabaseAndSchemaAsync(CancellationToken cancellationToken = default)
        {
            var builder = new NpgsqlConnectionStringBuilder(_connectionString);
            if (string.IsNullOrWhiteSpace(builder.Database))
                throw new InvalidOperationException("В строке подключения не указана база данных.");

            var databaseName = builder.Database!;
            builder.Database = "postgres";
            await using (var admin = new NpgsqlConnection(builder.ConnectionString))
            {
                await admin.OpenAsync(cancellationToken);
                using var exists = new NpgsqlCommand(
                    "select 1 from pg_database where datname = @name;", admin);
                exists.Parameters.AddWithValue("name", databaseName);
                if (await exists.ExecuteScalarAsync(cancellationToken) == null)
                {
                    var quoted = "\"" + databaseName.Replace("\"", "\"\"") + "\"";
                    using var create = new NpgsqlCommand("create database " + quoted + ";", admin);
                    await create.ExecuteNonQueryAsync(cancellationToken);
                    DatabaseLogger.Info("База данных создана: " + databaseName + ".");
                }
            }

            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var schema = new NpgsqlCommand(ReadEmbeddedSql(), connection);
            await schema.ExecuteNonQueryAsync(cancellationToken);
            using var extra = new NpgsqlCommand("""
                create table if not exists calculation_data (
                    id bigint generated by default as identity primary key,
                    object_id bigint not null references objects(id) on delete cascade,
                    calc_number character varying(50) not null,
                    source_file text,
                    sections_json jsonb not null,
                    created_at timestamp with time zone not null default now(),
                    updated_at timestamp with time zone not null default now(),
                    constraint uq_calculation_data_object_number unique (object_id, calc_number)
                );
                """, connection);
            await extra.ExecuteNonQueryAsync(cancellationToken);
            using var profile = new NpgsqlCommand("""
                create table if not exists object_profiles (
                    object_id bigint primary key references objects(id) on delete cascade,
                    profile_json jsonb not null,
                    updated_at timestamp with time zone not null default now()
                );
                """, connection);
            await profile.ExecuteNonQueryAsync(cancellationToken);
            using var results = new NpgsqlCommand("""
                create table if not exists calc_main_results (
                    calculation_id bigint primary key references calculations(id) on delete cascade,
                    throughput_m3s numeric,
                    max_flow_m3s numeric,
                    min_flow_m3s numeric,
                    avg_velocity_ms numeric,
                    upstream_level_m numeric,
                    downstream_level_m numeric,
                    efficiency_pct numeric,
                    annual_generation_mkwh numeric,
                    reliability_coeff numeric
                );
                """, connection);
            await results.ExecuteNonQueryAsync(cancellationToken);
            using var seed = new NpgsqlCommand("""
                insert into object_types (code, name)
                values ('hydro_node', 'Гидроузел')
                on conflict (code) do nothing;
                """, connection);
            await seed.ExecuteNonQueryAsync(cancellationToken);
            DatabaseLogger.Info("Миграции и служебная схема применены.");
        }

        public async Task SaveCalculationAsync(long objectId, string sectionsJson,
            string sourceFile, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(sectionsJson))
                throw new InvalidOperationException("Нельзя сохранить расчёт без створов.");

            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand("""
                insert into calculation_data (object_id, calc_number, source_file, sections_json)
                values (@object_id, 'flood-zone', @source_file, cast(@sections_json as jsonb))
                on conflict (object_id, calc_number) do update set
                    source_file = excluded.source_file,
                    sections_json = excluded.sections_json,
                    updated_at = now();
                """, connection);
            command.Parameters.AddWithValue("object_id", objectId);
            command.Parameters.AddWithValue("source_file", (object)sourceFile ?? DBNull.Value);
            command.Parameters.AddWithValue("sections_json", sectionsJson);
            await command.ExecuteNonQueryAsync(cancellationToken);
            using var calculation = new NpgsqlCommand("""
                insert into calculations (object_id, calc_number, name, mode, status, performed_at)
                values (@object_id, 'flood-zone', 'Расчёт зоны затопления', 'Просмотр', 1, now())
                on conflict (object_id, calc_number) do update set performed_at = now()
                returning id;
                """, connection);
            calculation.Parameters.AddWithValue("object_id", objectId);
            var calculationId = Convert.ToInt64(await calculation.ExecuteScalarAsync(cancellationToken));
            var sections = JsonSerializer.Deserialize<List<CalculationSection>>(sectionsJson)
                ?? new List<CalculationSection>();
            var maxFlow = sections.Count == 0 ? 0 : sections.Max(x => x.MaxDepth);
            var minFlow = sections.Count == 0 ? 0 : sections.Min(x => x.MaxDepth);
            var avgVelocity = sections.Count == 0 ? 0 : sections.Average(x => x.MaxVelocity);
            var upstream = sections.Count == 0 ? 0 : sections.Max(x => x.WaterLevel);
            using var result = new NpgsqlCommand("""
                insert into calc_main_results
                    (calculation_id, throughput_m3s, max_flow_m3s, min_flow_m3s,
                     avg_velocity_ms, upstream_level_m, downstream_level_m,
                     efficiency_pct, annual_generation_mkwh, reliability_coeff)
                values (@id, @throughput, @max_flow, @min_flow, @velocity,
                        @upstream, @downstream, 0, 0, 0)
                on conflict (calculation_id) do update set
                    throughput_m3s = excluded.throughput_m3s,
                    max_flow_m3s = excluded.max_flow_m3s,
                    min_flow_m3s = excluded.min_flow_m3s,
                    avg_velocity_ms = excluded.avg_velocity_ms,
                    upstream_level_m = excluded.upstream_level_m;
                """, connection);
            result.Parameters.AddWithValue("id", calculationId);
            result.Parameters.AddWithValue("throughput", sections.Sum(x => x.FloodWidthLeft + x.FloodWidthRight));
            result.Parameters.AddWithValue("max_flow", maxFlow);
            result.Parameters.AddWithValue("min_flow", minFlow);
            result.Parameters.AddWithValue("velocity", avgVelocity);
            result.Parameters.AddWithValue("upstream", upstream);
            result.Parameters.AddWithValue("downstream", sections.Count == 0 ? 0 : sections.Min(x => x.WaterLevel));
            await result.ExecuteNonQueryAsync(cancellationToken);
            DatabaseLogger.Info("Расчёт сохранён. Объект ID: " + objectId + ".");
        }

        private sealed class CalculationSection
        {
            public double WaterLevel { get; set; }
            public double MaxDepth { get; set; }
            public double MaxVelocity { get; set; }
            public double FloodWidthLeft { get; set; }
            public double FloodWidthRight { get; set; }
        }

        public async Task<SavedCalculation?> LoadCalculationAsync(long objectId,
            CancellationToken cancellationToken = default)
        {
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand("""
                select source_file, sections_json
                from calculation_data
                where object_id = @object_id and calc_number = 'flood-zone'
                limit 1;
                """, connection);
            command.Parameters.AddWithValue("object_id", objectId);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken);
            if (!await reader.ReadAsync(cancellationToken))
                return null;
            var source = reader.IsDBNull(0) ? "" : reader.GetString(0);
            return new SavedCalculation(reader.GetString(1), source);
        }

        private static string ReadEmbeddedSql()
        {
            var assembly = typeof(FloodZoneConnection).Assembly;
            using var stream = assembly.GetManifestResourceStream("FloodZoneDb.Migrations.InitialCreate.sql")
                ?? throw new InvalidOperationException("В сборку не включён SQL миграции.");
            using var reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }
        public sealed class SavedCalculation
        {
            public SavedCalculation(string sectionsJson, string sourceFile)
            {
                SectionsJson = sectionsJson;
                SourceFile = sourceFile;
            }

            public string SectionsJson { get; }
            public string SourceFile { get; }
        }

    public async Task<IReadOnlyList<DatabaseObject>> LoadObjectsAsync(
        CancellationToken cancellationToken = default)
    {
        const string sql = """
            select o.id, o.parent_id, ot.code, ot.name, o.name, o.sort_order,
                   o.is_active, o.updated_at
            from objects o
            inner join object_types ot on ot.id = o.object_type_id
            where o.is_active = true
            order by ot.name, o.sort_order, o.name;
            """;

        try
        {
            var result = new List<DatabaseObject>();
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand(sql, connection);
            using var reader = await command.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                result.Add(new DatabaseObject
                {
                    Id = reader.GetInt64(0),
                    ParentId = reader.IsDBNull(1) ? null : reader.GetInt64(1),
                    TypeCode = reader.GetString(2),
                    TypeName = reader.GetString(3),
                    Name = reader.GetString(4),
                    SortOrder = reader.GetInt32(5),
                    IsActive = reader.GetBoolean(6),
                    UpdatedAt = reader.GetDateTime(7)
                });
            }

            DatabaseLogger.Info("Загружено объектов из PostgreSQL: " + result.Count + ".");
            return result;
        }
        catch (Exception ex)
        {
            DatabaseLogger.Error("Ошибка загрузки объектов из PostgreSQL.", ex);
            throw;
        }
    }

    public async Task<long> CreateObjectAsync(
        string typeCode,
        string name,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(typeCode))
            throw new ArgumentException("Тип объекта не задан.", nameof(typeCode));
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Наименование объекта не задано.", nameof(name));

        const string sql = """
            insert into objects (object_type_id, name, sort_order, is_active, created_at, updated_at)
            select id, @name, coalesce((select max(sort_order) + 1 from objects), 0), true, now(), now()
            from object_types
            where code = @type_code
            returning id;
            """;

        try
        {
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand(sql, connection);
            command.Parameters.AddWithValue("type_code", typeCode);
            command.Parameters.AddWithValue("name", name);
            var result = await command.ExecuteScalarAsync(cancellationToken);
            if (result == null || result == DBNull.Value)
                throw new InvalidOperationException($"Тип объекта '{typeCode}' не найден в справочнике.");
            var id = Convert.ToInt64(result);
            DatabaseLogger.Info("Объект сохранён в PostgreSQL. ID: " + id + ".");
            return id;
        }

        catch (Exception ex)
        {
            DatabaseLogger.Error("Ошибка создания объекта в PostgreSQL. Тип: " + typeCode + ".", ex);
            throw;
        }
    }

    public async Task EnsureObjectTypeAsync(
        string code,
        string name,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(code))
            throw new ArgumentException("Тип объекта не задан.", nameof(code));

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);
        using var command = new NpgsqlCommand("""
            insert into object_types (code, name)
            values (@code, @name)
            on conflict (code) do update set name = excluded.name;
            """, connection);
        command.Parameters.AddWithValue("code", code.Trim());
        command.Parameters.AddWithValue("name", string.IsNullOrWhiteSpace(name) ? code.Trim() : name.Trim());
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task DeleteObjectTypeAsync(
        string code,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(code))
            throw new ArgumentException("Тип объекта не задан.", nameof(code));

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);
        using var command = new NpgsqlCommand("""
            delete from object_types t
            where t.code = @code
              and not exists (select 1 from objects o where o.object_type_id = t.id)
            returning t.id;
            """, connection);
        command.Parameters.AddWithValue("code", code.Trim());
        if (await command.ExecuteScalarAsync(cancellationToken) == null)
            throw new InvalidOperationException("Тип используется объектами или не найден.");
    }

    public async Task DeleteObjectAsync(
        long objectId,
        CancellationToken cancellationToken = default)
    {
        if (objectId <= 0)
            throw new ArgumentOutOfRangeException(nameof(objectId));

        try
        {
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand(
                "delete from objects where id = @object_id returning id;", connection);
            command.Parameters.AddWithValue("object_id", objectId);
            var deleted = await command.ExecuteScalarAsync(cancellationToken);
            if (deleted == null || deleted == DBNull.Value)
                throw new InvalidOperationException("Выбранный объект не найден.");

            DatabaseLogger.Info("Объект удалён из PostgreSQL. ID: " + objectId + ".");
        }
        catch (Exception ex)
        {
            DatabaseLogger.Error("Ошибка удаления объекта из PostgreSQL. ID: " + objectId + ".", ex);
            throw;
        }
    }

    public async Task UpdateObjectAsync(
            long objectId, string typeCode, string name,
            CancellationToken cancellationToken = default)
        {
            if (objectId <= 0)
                throw new ArgumentOutOfRangeException(nameof(objectId));
            if (string.IsNullOrWhiteSpace(typeCode))
                throw new ArgumentException("Тип объекта не задан.", nameof(typeCode));
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("Наименование объекта не задано.", nameof(name));

            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand("""
                update objects
                set object_type_id = (select id from object_types where code = @type_code),
                    name = @name,
                    updated_at = now()
                where id = @object_id;
                """, connection);
            command.Parameters.AddWithValue("object_id", objectId);
            command.Parameters.AddWithValue("type_code", typeCode);
            command.Parameters.AddWithValue("name", name);
            if (await command.ExecuteNonQueryAsync(cancellationToken) == 0)
                throw new InvalidOperationException("Выбранный объект не найден.");
            DatabaseLogger.Info("Карточка объекта обновлена. ID: " + objectId + ".");
        }
        

        public async Task<ObjectProfile?> LoadObjectProfileAsync(
            long objectId, CancellationToken cancellationToken = default)
        {
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand(
                "select profile_json from object_profiles where object_id = @object_id;", connection);
            command.Parameters.AddWithValue("object_id", objectId);
            var value = await command.ExecuteScalarAsync(cancellationToken);
            if (value == null || value == DBNull.Value)
                return null;
            return JsonSerializer.Deserialize<ObjectProfile>(Convert.ToString(value)!);
        }

        public async Task SaveObjectProfileAsync(
            long objectId, ObjectProfile profile, CancellationToken cancellationToken = default)
        {
            if (objectId <= 0)
                throw new ArgumentOutOfRangeException(nameof(objectId));
            if (profile == null)
                throw new ArgumentNullException(nameof(profile));

            var json = JsonSerializer.Serialize(profile);
            await using var connection = new NpgsqlConnection(_connectionString);
            await connection.OpenAsync(cancellationToken);
            using var command = new NpgsqlCommand("""
                insert into object_profiles (object_id, profile_json, updated_at)
                values (@object_id, cast(@profile_json as jsonb), now())
                on conflict (object_id) do update set
                    profile_json = excluded.profile_json,
                    updated_at = now();
                """, connection);
            command.Parameters.AddWithValue("object_id", objectId);
            command.Parameters.AddWithValue("profile_json", json);
            await command.ExecuteNonQueryAsync(cancellationToken);
            DatabaseLogger.Info("Профиль объекта сохранён. ID: " + objectId + ".");
        }
    }
