<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>FloodZoneDb.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.4" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\FloodZoneDb\Migrations\InitialCreate.sql"
                      Link="Migrations\InitialCreate.sql"
                      LogicalName="FloodZoneDb.Migrations.InitialCreate.sql" />
    <EmbeddedResource Include="..\FloodZoneDb\Migrations\CreateIsodats.sql"
                      Link="Migrations\CreateIsodats.sql"
                      LogicalName="FloodZoneDb.Migrations.CreateIsodats.sql" />
    <EmbeddedResource Include="..\FloodZoneDb\Migrations\CreateIsodatHydraulicPoints.sql"
                      Link="Migrations\CreateIsodatHydraulicPoints.sql"
                      LogicalName="FloodZoneDb.Migrations.CreateIsodatHydraulicPoints.sql" />
  </ItemGroup>
</Project>
