// <auto-generated />
using System;
using FloodZoneDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FloodZoneDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929162524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bank_side", new[] { "L", "P" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "calc_status", new[] { "draft", "computed", "approved", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "object_class", new[] { "I", "II", "III", "IV" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reliability_category", new[] { "особо ответственное", "ответственное", "пониженное" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FloodZoneDb.Domain.Building", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<decimal?>("AreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("area_m2");

                    b.Property<decimal?>("HeightM")
                        .HasColumnType("numeric")
                        .HasColumnName("height_m");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.HasKey("ObjectId")
                        .HasName("pk_buildings");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcFlowProvision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal>("FlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("flow_m3s");

                    b.Property<decimal>("ProvisionPct")
                        .HasColumnType("numeric")
                        .HasColumnName("provision_pct");

                    b.HasKey("Id")
                        .HasName("pk_calc_flow_provision");

                    b.HasIndex("CalculationId")
                        .HasDatabaseName("ix_calc_flow_provision_calculation_id");

                    b.ToTable("calc_flow_provision", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcHydrological", b =>
                {
                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal?>("AvgAnnualRunoffKm3")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_annual_runoff_km3");

                    b.Property<decimal?>("CatchmentAreaKm2")
                        .HasColumnType("numeric")
                        .HasColumnName("catchment_area_km2");

                    b.Property<decimal?>("MaxFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("max_flow_m3s");

                    b.Property<decimal?>("MinFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("min_flow_m3s");

                    b.Property<decimal?>("ProvisionPct")
                        .HasColumnType("numeric")
                        .HasColumnName("provision_pct");

                    b.HasKey("CalculationId")
                        .HasName("pk_calc_hydrological");

                    b.ToTable("calc_hydrological", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcInitial", b =>
                {
                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal?>("DeadVolumeLevelM")
                        .HasColumnType("numeric")
                        .HasColumnName("dead_volume_level_m");

                    b.Property<decimal?>("NormalHeadwaterM")
                        .HasColumnType("numeric")
                        .HasColumnName("normal_headwater_m");

                    b.Property<decimal?>("ReservoirFullVolumeMlnM3")
                        .HasColumnType("numeric")
                        .HasColumnName("reservoir_full_volume_mln_m3");

                    b.Property<decimal?>("ReservoirUsefulVolumeMlnM3")
                        .HasColumnType("numeric")
                        .HasColumnName("reservoir_useful_volume_mln_m3");

                    b.Property<decimal?>("RoughnessCoeffN")
                        .HasColumnType("numeric")
                        .HasColumnName("roughness_coeff_n");

                    b.Property<decimal?>("WaterTemperatureC")
                        .HasColumnType("numeric")
                        .HasColumnName("water_temperature_c");

                    b.HasKey("CalculationId")
                        .HasName("pk_calc_initial");

                    b.ToTable("calc_initial", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcMainResult", b =>
                {
                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal?>("AnnualGenerationMkwh")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_generation_mkwh");

                    b.Property<decimal?>("AvgVelocityMs")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_velocity_ms");

                    b.Property<decimal?>("DownstreamLevelM")
                        .HasColumnType("numeric")
                        .HasColumnName("downstream_level_m");

                    b.Property<decimal?>("EfficiencyPct")
                        .HasColumnType("numeric")
                        .HasColumnName("efficiency_pct");

                    b.Property<decimal?>("MaxFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("max_flow_m3s");

                    b.Property<decimal?>("MinFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("min_flow_m3s");

                    b.Property<decimal?>("ReliabilityCoeff")
                        .HasColumnType("numeric")
                        .HasColumnName("reliability_coeff");

                    b.Property<decimal?>("ThroughputM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("throughput_m3s");

                    b.Property<decimal?>("UpstreamLevelM")
                        .HasColumnType("numeric")
                        .HasColumnName("upstream_level_m");

                    b.HasKey("CalculationId")
                        .HasName("pk_calc_main_results");

                    b.ToTable("calc_main_results", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("media_type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_calc_media");

                    b.HasIndex("CalculationId")
                        .HasDatabaseName("ix_calc_media_calculation_id");

                    b.ToTable("calc_media", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcOperationMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AvgFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_flow_m3s");

                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal?>("DownstreamLevelM")
                        .HasColumnType("numeric")
                        .HasColumnName("downstream_level_m");

                    b.Property<decimal?>("MaxFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("max_flow_m3s");

                    b.Property<decimal?>("MinFlowM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("min_flow_m3s");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("period");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("period_name");

                    b.Property<decimal?>("UpstreamLevelM")
                        .HasColumnType("numeric")
                        .HasColumnName("upstream_level_m");

                    b.HasKey("Id")
                        .HasName("pk_calc_operation_modes");

                    b.HasIndex("CalculationId")
                        .HasDatabaseName("ix_calc_operation_modes_calculation_id");

                    b.ToTable("calc_operation_modes", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcPowerGeneration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal>("GenerationMkwh")
                        .HasColumnType("numeric")
                        .HasColumnName("generation_mkwh");

                    b.Property<short>("MonthNum")
                        .HasColumnType("smallint")
                        .HasColumnName("month_num");

                    b.HasKey("Id")
                        .HasName("pk_calc_power_generation");

                    b.HasIndex("CalculationId")
                        .HasDatabaseName("ix_calc_power_generation_calculation_id");

                    b.ToTable("calc_power_generation", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcStructural", b =>
                {
                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal?>("CrestWidthM")
                        .HasColumnType("numeric")
                        .HasColumnName("crest_width_m");

                    b.Property<decimal?>("DamLengthM")
                        .HasColumnType("numeric")
                        .HasColumnName("dam_length_m");

                    b.Property<decimal?>("DamMaxHeightM")
                        .HasColumnType("numeric")
                        .HasColumnName("dam_max_height_m");

                    b.Property<int?>("DamTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("dam_type_id");

                    b.Property<decimal?>("InstalledPowerMw")
                        .HasColumnType("numeric")
                        .HasColumnName("installed_power_mw");

                    b.Property<int?>("SpillwayTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("spillway_type_id");

                    b.Property<int?>("SpillwaysCount")
                        .HasColumnType("integer")
                        .HasColumnName("spillways_count");

                    b.Property<int?>("TurbineTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("turbine_type_id");

                    b.Property<int?>("UnitsCount")
                        .HasColumnType("integer")
                        .HasColumnName("units_count");

                    b.HasKey("CalculationId")
                        .HasName("pk_calc_structural");

                    b.HasIndex("DamTypeId")
                        .HasDatabaseName("ix_calc_structural_dam_type_id");

                    b.HasIndex("SpillwayTypeId")
                        .HasDatabaseName("ix_calc_structural_spillway_type_id");

                    b.HasIndex("TurbineTypeId")
                        .HasDatabaseName("ix_calc_structural_turbine_type_id");

                    b.ToTable("calc_structural", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcWaterBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CalculationId")
                        .HasColumnType("bigint")
                        .HasColumnName("calculation_id");

                    b.Property<decimal>("SharePct")
                        .HasColumnType("numeric")
                        .HasColumnName("share_pct");

                    b.Property<string>("UseCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("use_category");

                    b.HasKey("Id")
                        .HasName("pk_calc_water_balance");

                    b.HasIndex("CalculationId")
                        .HasDatabaseName("ix_calc_water_balance_calculation_id");

                    b.ToTable("calc_water_balance", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Calculation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CalcNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calc_number");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_calculations");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("ix_calculations_performed_by_user_id");

                    b.HasIndex("ObjectId", "CalcNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_calculations_object_id_calc_number");

                    b.ToTable("calculations", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Dam", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<int?>("DamTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("dam_type_id");

                    b.Property<decimal?>("LengthM")
                        .HasColumnType("numeric")
                        .HasColumnName("length_m");

                    b.Property<decimal?>("MaxHeightM")
                        .HasColumnType("numeric")
                        .HasColumnName("max_height_m");

                    b.Property<decimal?>("MinWaterLevelM")
                        .HasColumnType("numeric")
                        .HasColumnName("min_water_level_m");

                    b.Property<decimal?>("NormalHeadwaterM")
                        .HasColumnType("numeric")
                        .HasColumnName("normal_headwater_m");

                    b.Property<decimal?>("ReservoirVolumeMlnM3")
                        .HasColumnType("numeric")
                        .HasColumnName("reservoir_volume_mln_m3");

                    b.HasKey("ObjectId")
                        .HasName("pk_dams");

                    b.HasIndex("DamTypeId")
                        .HasDatabaseName("ix_dams_dam_type_id");

                    b.ToTable("dams", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.DamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dam_types");

                    b.ToTable("dam_types", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Equipment", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type_id");

                    b.Property<int?>("GeneratorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("generator_type_id");

                    b.Property<DateOnly?>("InstalledAt")
                        .HasColumnType("date")
                        .HasColumnName("installed_at");

                    b.Property<decimal?>("PowerMw")
                        .HasColumnType("numeric")
                        .HasColumnName("power_mw");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("TurbineTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("turbine_type_id");

                    b.Property<decimal?>("VoltageKv")
                        .HasColumnType("numeric")
                        .HasColumnName("voltage_kv");

                    b.HasKey("ObjectId")
                        .HasName("pk_equipment");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("ix_equipment_equipment_type_id");

                    b.HasIndex("GeneratorTypeId")
                        .HasDatabaseName("ix_equipment_generator_type_id");

                    b.HasIndex("TurbineTypeId")
                        .HasDatabaseName("ix_equipment_turbine_type_id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_equipment_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_types_code");

                    b.ToTable("equipment_types", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.GeneratorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_generator_types");

                    b.ToTable("generator_types", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.GtsObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("object_type_id");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_objects");

                    b.HasIndex("ObjectTypeId")
                        .HasDatabaseName("ix_objects_object_type_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_objects_parent_id");

                    b.ToTable("objects", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.HydroNode", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<decimal?>("AvgAnnualGenerationMkwh")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_annual_generation_mkwh");

                    b.Property<string>("BalanceAffiliation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("balance_affiliation");

                    b.Property<DateOnly?>("CommissioningDate")
                        .HasColumnType("date")
                        .HasColumnName("commissioning_date");

                    b.Property<int?>("DesignOrgId")
                        .HasColumnType("integer")
                        .HasColumnName("design_org_id");

                    b.Property<decimal?>("DesignPowerMw")
                        .HasColumnType("numeric")
                        .HasColumnName("design_power_mw");

                    b.Property<int?>("GtsClass")
                        .HasColumnType("integer")
                        .HasColumnName("gts_class");

                    b.Property<int?>("OwnerOrgId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_org_id");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_code");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<int?>("ReliabilityCategory")
                        .HasColumnType("integer")
                        .HasColumnName("reliability_category");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsible_person");

                    b.Property<int?>("RiverId")
                        .HasColumnType("integer")
                        .HasColumnName("river_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int?>("UnitsCount")
                        .HasColumnType("integer")
                        .HasColumnName("units_count");

                    b.HasKey("ObjectId")
                        .HasName("pk_hydro_nodes");

                    b.HasIndex("DesignOrgId")
                        .HasDatabaseName("ix_hydro_nodes_design_org_id");

                    b.HasIndex("OwnerOrgId")
                        .HasDatabaseName("ix_hydro_nodes_owner_org_id");

                    b.HasIndex("RiverId")
                        .HasDatabaseName("ix_hydro_nodes_river_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_hydro_nodes_status_id");

                    b.ToTable("hydro_nodes", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectCondition", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("AccidentRate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accident_rate");

                    b.Property<DateOnly?>("LastInspectionAt")
                        .HasColumnType("date")
                        .HasColumnName("last_inspection_at");

                    b.Property<DateOnly?>("NextInspectionAt")
                        .HasColumnType("date")
                        .HasColumnName("next_inspection_at");

                    b.Property<decimal?>("PhysicalWearPct")
                        .HasColumnType("numeric")
                        .HasColumnName("physical_wear_pct");

                    b.Property<string>("SpecialMarks")
                        .HasColumnType("text")
                        .HasColumnName("special_marks");

                    b.Property<string>("TechCondition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tech_condition");

                    b.HasKey("ObjectId")
                        .HasName("pk_object_condition");

                    b.ToTable("object_condition", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectLocation", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("District")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("district");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<int?>("SubjectRfId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_rf_id");

                    b.HasKey("ObjectId")
                        .HasName("pk_object_location");

                    b.HasIndex("SubjectRfId")
                        .HasDatabaseName("ix_object_location_subject_rf_id");

                    b.ToTable("object_location", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_object_media");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_object_media_object_id");

                    b.ToTable("object_media", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectNote", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.HasKey("ObjectId")
                        .HasName("pk_object_notes");

                    b.ToTable("object_notes", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectQuickInfo", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("ObjectId")
                        .HasName("pk_object_quick_info");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_object_quick_info_updated_by_user_id");

                    b.ToTable("object_quick_info", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectTechnicalSpec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("SpecKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("spec_key");

                    b.Property<string>("SpecValue")
                        .HasColumnType("text")
                        .HasColumnName("spec_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_object_technical_specs");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_object_technical_specs_object_id");

                    b.ToTable("object_technical_specs", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_code");

                    b.HasKey("Id")
                        .HasName("pk_object_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_object_types_code");

                    b.ToTable("object_types", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Ogrn")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ogrn");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Inn")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_inn");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.River", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasinAreaKm2")
                        .HasColumnType("numeric")
                        .HasColumnName("basin_area_km2");

                    b.Property<decimal?>("LengthKm")
                        .HasColumnType("numeric")
                        .HasColumnName("length_km");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_rivers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_rivers_name");

                    b.ToTable("rivers", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Spillway", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<decimal?>("MaxCapacityM3s")
                        .HasColumnType("numeric")
                        .HasColumnName("max_capacity_m3s");

                    b.Property<int?>("OpeningsCount")
                        .HasColumnType("integer")
                        .HasColumnName("openings_count");

                    b.Property<int?>("SpillwayTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("spillway_type_id");

                    b.HasKey("ObjectId")
                        .HasName("pk_spillways");

                    b.HasIndex("SpillwayTypeId")
                        .HasDatabaseName("ix_spillways_spillway_type_id");

                    b.ToTable("spillways", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.SpillwayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_spillway_types");

                    b.ToTable("spillway_types", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_statuses_code");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.SubjectRf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subjects_rf");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_rf_name");

                    b.ToTable("subjects_rf", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.TurbineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_turbine_types");

                    b.ToTable("turbine_types", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Building", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_objects_object_id");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcFlowProvision", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_flow_provision_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcHydrological", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_hydrological_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcInitial", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_initial_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcMainResult", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_main_results_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcMedia", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_media_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcOperationMode", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_operation_modes_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcPowerGeneration", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_power_generation_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcStructural", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_structural_calculations_calculation_id");

                    b.HasOne("FloodZoneDb.Domain.DamType", "DamType")
                        .WithMany()
                        .HasForeignKey("DamTypeId")
                        .HasConstraintName("fk_calc_structural_dam_types_dam_type_id");

                    b.HasOne("FloodZoneDb.Domain.SpillwayType", "SpillwayType")
                        .WithMany()
                        .HasForeignKey("SpillwayTypeId")
                        .HasConstraintName("fk_calc_structural_spillway_types_spillway_type_id");

                    b.HasOne("FloodZoneDb.Domain.TurbineType", "TurbineType")
                        .WithMany()
                        .HasForeignKey("TurbineTypeId")
                        .HasConstraintName("fk_calc_structural_turbine_types_turbine_type_id");

                    b.Navigation("Calculation");

                    b.Navigation("DamType");

                    b.Navigation("SpillwayType");

                    b.Navigation("TurbineType");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.CalcWaterBalance", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calc_water_balance_calculations_calculation_id");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Calculation", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calculations_objects_object_id");

                    b.HasOne("FloodZoneDb.Domain.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .HasConstraintName("fk_calculations_users_performed_by_user_id");

                    b.Navigation("Object");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Dam", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.DamType", "DamType")
                        .WithMany()
                        .HasForeignKey("DamTypeId")
                        .HasConstraintName("fk_dams_dam_types_dam_type_id");

                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dams_objects_object_id");

                    b.Navigation("DamType");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Equipment", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .HasConstraintName("fk_equipment_equipment_types_equipment_type_id");

                    b.HasOne("FloodZoneDb.Domain.GeneratorType", "GeneratorType")
                        .WithMany()
                        .HasForeignKey("GeneratorTypeId")
                        .HasConstraintName("fk_equipment_generator_types_generator_type_id");

                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_objects_object_id");

                    b.HasOne("FloodZoneDb.Domain.TurbineType", "TurbineType")
                        .WithMany()
                        .HasForeignKey("TurbineTypeId")
                        .HasConstraintName("fk_equipment_turbine_types_turbine_type_id");

                    b.Navigation("EquipmentType");

                    b.Navigation("GeneratorType");

                    b.Navigation("Object");

                    b.Navigation("TurbineType");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.GtsObject", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_objects_object_types_object_type_id");

                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_objects_objects_parent_id");

                    b.Navigation("ObjectType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.HydroNode", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.Organization", "DesignOrg")
                        .WithMany()
                        .HasForeignKey("DesignOrgId")
                        .HasConstraintName("fk_hydro_nodes_organizations_design_org_id");

                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hydro_nodes_objects_object_id");

                    b.HasOne("FloodZoneDb.Domain.Organization", "OwnerOrg")
                        .WithMany()
                        .HasForeignKey("OwnerOrgId")
                        .HasConstraintName("fk_hydro_nodes_organizations_owner_org_id");

                    b.HasOne("FloodZoneDb.Domain.River", "River")
                        .WithMany()
                        .HasForeignKey("RiverId")
                        .HasConstraintName("fk_hydro_nodes_rivers_river_id");

                    b.HasOne("FloodZoneDb.Domain.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .HasConstraintName("fk_hydro_nodes_statuses_status_id");

                    b.Navigation("DesignOrg");

                    b.Navigation("Object");

                    b.Navigation("OwnerOrg");

                    b.Navigation("River");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectCondition", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_condition_objects_object_id");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectLocation", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_location_objects_object_id");

                    b.HasOne("FloodZoneDb.Domain.SubjectRf", "SubjectRf")
                        .WithMany()
                        .HasForeignKey("SubjectRfId")
                        .HasConstraintName("fk_object_location_subjects_rf_subject_rf_id");

                    b.Navigation("Object");

                    b.Navigation("SubjectRf");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectMedia", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_media_objects_object_id");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectNote", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_notes_objects_object_id");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectQuickInfo", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_quick_info_objects_object_id");

                    b.HasOne("FloodZoneDb.Domain.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("fk_object_quick_info_users_updated_by_user_id");

                    b.Navigation("Object");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.ObjectTechnicalSpec", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_technical_specs_objects_object_id");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.Spillway", b =>
                {
                    b.HasOne("FloodZoneDb.Domain.GtsObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spillways_objects_object_id");

                    b.HasOne("FloodZoneDb.Domain.SpillwayType", "SpillwayType")
                        .WithMany()
                        .HasForeignKey("SpillwayTypeId")
                        .HasConstraintName("fk_spillways_spillway_types_spillway_type_id");

                    b.Navigation("Object");

                    b.Navigation("SpillwayType");
                });

            modelBuilder.Entity("FloodZoneDb.Domain.GtsObject", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
