create table if not exists isodats (
    id bigint generated by default as identity primary key,
    cross_section_number integer not null check (cross_section_number > 0),
    side text not null check (side in ('Left', 'Right')),
    isodat_type text not null check (
        isodat_type in ('Depth', 'Velocity', 'CalculatedFloodDuration', 'ActualFloodDuration')
    ),
    value numeric not null,
    distance_m numeric not null,
    source_sheet text not null,
    source_file_name text not null,
    source_file_sha256 char(64) not null,
    source_row integer not null check (source_row > 0),
    value_source_column text not null,
    distance_source_column text not null,
    constraint uq_isodats_source_cell unique
        (source_file_sha256, source_sheet, source_row, value_source_column)
);
