create table if not exists isodat_hydraulic_points (
    id bigint generated by default as identity primary key,
    source_isodat_id bigint not null unique references isodats(id),
    cross_section_number integer not null check (cross_section_number > 0),
    side text not null check (side in ('Left', 'Right')),
    x numeric not null,
    depth_h numeric,
    observed_velocity numeric,
    source_file_sha256 char(64) not null,
    source_sheet text not null,
    source_row integer not null check (source_row > 0),
    source_value_column text not null,
    interpretation text not null check (interpretation = 'EducationalSynthetic'),
    constraint ck_isodat_hydraulic_point_single_value
        check ((depth_h is null) <> (observed_velocity is null))
);

create index if not exists ix_isodat_hydraulic_points_profile
    on isodat_hydraulic_points (source_file_sha256, cross_section_number, side);
