CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TYPE bank_side AS ENUM ('L', 'P');
    CREATE TYPE calc_status AS ENUM ('draft', 'computed', 'approved', 'archived');
    CREATE TYPE object_class AS ENUM ('I', 'II', 'III', 'IV');
    CREATE TYPE reliability_category AS ENUM ('особо ответственное', 'ответственное', 'пониженное');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE dam_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT pk_dam_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE equipment_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(50) NOT NULL,
        name character varying(200) NOT NULL,
        CONSTRAINT pk_equipment_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE generator_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT pk_generator_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(50) NOT NULL,
        name character varying(200) NOT NULL,
        parent_code character varying(50),
        icon character varying(255),
        CONSTRAINT pk_object_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE organizations (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(300) NOT NULL,
        inn character varying(12),
        ogrn character varying(15),
        role character varying(50),
        CONSTRAINT pk_organizations PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE rivers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        length_km numeric,
        basin_area_km2 numeric,
        CONSTRAINT pk_rivers PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE spillway_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT pk_spillway_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE statuses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(50) NOT NULL,
        name character varying(200) NOT NULL,
        CONSTRAINT pk_statuses PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE subjects_rf (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        code character varying(10),
        CONSTRAINT pk_subjects_rf PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE turbine_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT pk_turbine_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        login character varying(100) NOT NULL,
        full_name character varying(200),
        role character varying(50) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE objects (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        parent_id bigint,
        object_type_id integer NOT NULL,
        name character varying(300) NOT NULL,
        sort_order integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_objects PRIMARY KEY (id),
        CONSTRAINT fk_objects_object_types_object_type_id FOREIGN KEY (object_type_id) REFERENCES object_types (id) ON DELETE CASCADE,
        CONSTRAINT fk_objects_objects_parent_id FOREIGN KEY (parent_id) REFERENCES objects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE buildings (
        object_id bigint NOT NULL,
        area_m2 numeric,
        height_m numeric,
        purpose text,
        CONSTRAINT pk_buildings PRIMARY KEY (object_id),
        CONSTRAINT fk_buildings_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calculations (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        object_id bigint NOT NULL,
        calc_number character varying(50) NOT NULL,
        name character varying(300) NOT NULL,
        mode character varying(50) NOT NULL,
        status integer NOT NULL,
        performed_by_user_id integer,
        performed_at timestamp with time zone NOT NULL,
        notes text,
        CONSTRAINT pk_calculations PRIMARY KEY (id),
        CONSTRAINT fk_calculations_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE,
        CONSTRAINT fk_calculations_users_performed_by_user_id FOREIGN KEY (performed_by_user_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE dams (
        object_id bigint NOT NULL,
        dam_type_id integer,
        length_m numeric,
        max_height_m numeric,
        normal_headwater_m numeric,
        min_water_level_m numeric,
        reservoir_volume_mln_m3 numeric,
        CONSTRAINT pk_dams PRIMARY KEY (object_id),
        CONSTRAINT fk_dams_dam_types_dam_type_id FOREIGN KEY (dam_type_id) REFERENCES dam_types (id),
        CONSTRAINT fk_dams_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE equipment (
        object_id bigint NOT NULL,
        equipment_type_id integer,
        turbine_type_id integer,
        generator_type_id integer,
        voltage_kv numeric,
        power_mw numeric,
        serial_number character varying(100),
        installed_at date,
        CONSTRAINT pk_equipment PRIMARY KEY (object_id),
        CONSTRAINT fk_equipment_equipment_types_equipment_type_id FOREIGN KEY (equipment_type_id) REFERENCES equipment_types (id),
        CONSTRAINT fk_equipment_generator_types_generator_type_id FOREIGN KEY (generator_type_id) REFERENCES generator_types (id),
        CONSTRAINT fk_equipment_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE,
        CONSTRAINT fk_equipment_turbine_types_turbine_type_id FOREIGN KEY (turbine_type_id) REFERENCES turbine_types (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE hydro_nodes (
        object_id bigint NOT NULL,
        river_id integer,
        purpose text,
        commissioning_date date,
        owner_org_id integer,
        balance_affiliation character varying(200),
        responsible_person character varying(200),
        status_id integer,
        gts_class integer,
        reliability_category integer,
        design_org_id integer,
        project_code character varying(50),
        design_power_mw numeric,
        units_count integer,
        avg_annual_generation_mkwh numeric,
        CONSTRAINT pk_hydro_nodes PRIMARY KEY (object_id),
        CONSTRAINT fk_hydro_nodes_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE,
        CONSTRAINT fk_hydro_nodes_organizations_design_org_id FOREIGN KEY (design_org_id) REFERENCES organizations (id),
        CONSTRAINT fk_hydro_nodes_organizations_owner_org_id FOREIGN KEY (owner_org_id) REFERENCES organizations (id),
        CONSTRAINT fk_hydro_nodes_rivers_river_id FOREIGN KEY (river_id) REFERENCES rivers (id),
        CONSTRAINT fk_hydro_nodes_statuses_status_id FOREIGN KEY (status_id) REFERENCES statuses (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_condition (
        object_id bigint NOT NULL,
        physical_wear_pct numeric,
        tech_condition character varying(100),
        last_inspection_at date,
        next_inspection_at date,
        accident_rate character varying(100),
        special_marks text,
        CONSTRAINT pk_object_condition PRIMARY KEY (object_id),
        CONSTRAINT fk_object_condition_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_location (
        object_id bigint NOT NULL,
        subject_rf_id integer,
        district character varying(200),
        latitude numeric,
        longitude numeric,
        address text,
        CONSTRAINT pk_object_location PRIMARY KEY (object_id),
        CONSTRAINT fk_object_location_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE,
        CONSTRAINT fk_object_location_subjects_rf_subject_rf_id FOREIGN KEY (subject_rf_id) REFERENCES subjects_rf (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_media (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        object_id bigint NOT NULL,
        media_type character varying(20) NOT NULL,
        file_path text NOT NULL,
        caption text,
        uploaded_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_object_media PRIMARY KEY (id),
        CONSTRAINT fk_object_media_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_notes (
        object_id bigint NOT NULL,
        short_description text,
        remarks text,
        CONSTRAINT pk_object_notes PRIMARY KEY (object_id),
        CONSTRAINT fk_object_notes_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_profiles (
        object_id bigint NOT NULL,
        profile_json jsonb NOT NULL,
        updated_at timestamp with time zone NOT NULL DEFAULT now(),
        CONSTRAINT pk_object_profiles PRIMARY KEY (object_id),
        CONSTRAINT fk_object_profiles_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_quick_info (
        object_id bigint NOT NULL,
        last_updated_at timestamp with time zone NOT NULL,
        updated_by_user_id integer,
        CONSTRAINT pk_object_quick_info PRIMARY KEY (object_id),
        CONSTRAINT fk_object_quick_info_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE,
        CONSTRAINT fk_object_quick_info_users_updated_by_user_id FOREIGN KEY (updated_by_user_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE object_technical_specs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        object_id bigint NOT NULL,
        spec_key character varying(100) NOT NULL,
        spec_value text,
        unit character varying(30),
        CONSTRAINT pk_object_technical_specs PRIMARY KEY (id),
        CONSTRAINT fk_object_technical_specs_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE spillways (
        object_id bigint NOT NULL,
        spillway_type_id integer,
        max_capacity_m3s numeric,
        openings_count integer,
        CONSTRAINT pk_spillways PRIMARY KEY (object_id),
        CONSTRAINT fk_spillways_objects_object_id FOREIGN KEY (object_id) REFERENCES objects (id) ON DELETE CASCADE,
        CONSTRAINT fk_spillways_spillway_types_spillway_type_id FOREIGN KEY (spillway_type_id) REFERENCES spillway_types (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_flow_provision (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        calculation_id bigint NOT NULL,
        provision_pct numeric NOT NULL,
        flow_m3s numeric NOT NULL,
        CONSTRAINT pk_calc_flow_provision PRIMARY KEY (id),
        CONSTRAINT fk_calc_flow_provision_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_hydrological (
        calculation_id bigint NOT NULL,
        catchment_area_km2 numeric,
        avg_annual_runoff_km3 numeric,
        max_flow_m3s numeric,
        min_flow_m3s numeric,
        provision_pct numeric,
        CONSTRAINT pk_calc_hydrological PRIMARY KEY (calculation_id),
        CONSTRAINT fk_calc_hydrological_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_initial (
        calculation_id bigint NOT NULL,
        normal_headwater_m numeric,
        dead_volume_level_m numeric,
        reservoir_full_volume_mln_m3 numeric,
        reservoir_useful_volume_mln_m3 numeric,
        roughness_coeff_n numeric,
        water_temperature_c numeric,
        CONSTRAINT pk_calc_initial PRIMARY KEY (calculation_id),
        CONSTRAINT fk_calc_initial_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_main_results (
        calculation_id bigint NOT NULL,
        throughput_m3s numeric,
        max_flow_m3s numeric,
        min_flow_m3s numeric,
        avg_velocity_ms numeric,
        upstream_level_m numeric,
        downstream_level_m numeric,
        efficiency_pct numeric,
        annual_generation_mkwh numeric,
        reliability_coeff numeric,
        CONSTRAINT pk_calc_main_results PRIMARY KEY (calculation_id),
        CONSTRAINT fk_calc_main_results_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_media (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        calculation_id bigint NOT NULL,
        media_type character varying(30) NOT NULL,
        file_path text NOT NULL,
        caption text,
        uploaded_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_calc_media PRIMARY KEY (id),
        CONSTRAINT fk_calc_media_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_operation_modes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        calculation_id bigint NOT NULL,
        period character varying(50) NOT NULL,
        period_name character varying(100) NOT NULL,
        avg_flow_m3s numeric,
        max_flow_m3s numeric,
        min_flow_m3s numeric,
        upstream_level_m numeric,
        downstream_level_m numeric,
        CONSTRAINT pk_calc_operation_modes PRIMARY KEY (id),
        CONSTRAINT fk_calc_operation_modes_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_power_generation (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        calculation_id bigint NOT NULL,
        month_num smallint NOT NULL,
        generation_mkwh numeric NOT NULL,
        CONSTRAINT pk_calc_power_generation PRIMARY KEY (id),
        CONSTRAINT fk_calc_power_generation_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_structural (
        calculation_id bigint NOT NULL,
        dam_type_id integer,
        dam_length_m numeric,
        dam_max_height_m numeric,
        crest_width_m numeric,
        spillways_count integer,
        spillway_type_id integer,
        turbine_type_id integer,
        units_count integer,
        installed_power_mw numeric,
        CONSTRAINT pk_calc_structural PRIMARY KEY (calculation_id),
        CONSTRAINT fk_calc_structural_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE,
        CONSTRAINT fk_calc_structural_dam_types_dam_type_id FOREIGN KEY (dam_type_id) REFERENCES dam_types (id),
        CONSTRAINT fk_calc_structural_spillway_types_spillway_type_id FOREIGN KEY (spillway_type_id) REFERENCES spillway_types (id),
        CONSTRAINT fk_calc_structural_turbine_types_turbine_type_id FOREIGN KEY (turbine_type_id) REFERENCES turbine_types (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE TABLE calc_water_balance (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        calculation_id bigint NOT NULL,
        use_category character varying(100) NOT NULL,
        share_pct numeric NOT NULL,
        CONSTRAINT pk_calc_water_balance PRIMARY KEY (id),
        CONSTRAINT fk_calc_water_balance_calculations_calculation_id FOREIGN KEY (calculation_id) REFERENCES calculations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_flow_provision_calculation_id ON calc_flow_provision (calculation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_media_calculation_id ON calc_media (calculation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_operation_modes_calculation_id ON calc_operation_modes (calculation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_power_generation_calculation_id ON calc_power_generation (calculation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_structural_dam_type_id ON calc_structural (dam_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_structural_spillway_type_id ON calc_structural (spillway_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_structural_turbine_type_id ON calc_structural (turbine_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calc_water_balance_calculation_id ON calc_water_balance (calculation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_calculations_object_id_calc_number ON calculations (object_id, calc_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_calculations_performed_by_user_id ON calculations (performed_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_dams_dam_type_id ON dams (dam_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_equipment_equipment_type_id ON equipment (equipment_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_equipment_generator_type_id ON equipment (generator_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_equipment_turbine_type_id ON equipment (turbine_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_equipment_types_code ON equipment_types (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_hydro_nodes_design_org_id ON hydro_nodes (design_org_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_hydro_nodes_owner_org_id ON hydro_nodes (owner_org_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_hydro_nodes_river_id ON hydro_nodes (river_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_hydro_nodes_status_id ON hydro_nodes (status_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_object_location_subject_rf_id ON object_location (subject_rf_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_object_media_object_id ON object_media (object_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_object_quick_info_updated_by_user_id ON object_quick_info (updated_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_object_technical_specs_object_id ON object_technical_specs (object_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_object_types_code ON object_types (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_objects_object_type_id ON objects (object_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_objects_parent_id ON objects (parent_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_organizations_inn ON organizations (inn);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_rivers_name ON rivers (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE INDEX ix_spillways_spillway_type_id ON spillways (spillway_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_statuses_code ON statuses (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_subjects_rf_name ON subjects_rf (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_login ON users (login);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260929162524_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260929162524_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;
